<?php
namespace Halftheory\Lib\helpers;

use Halftheory\Lib\Filters;

#[AllowDynamicProperties]
class Security_Common extends Filters {

	public static $handle;
	protected static $instance;
	protected $data = array();

	protected static $filters = array();

	public function __construct( $autoload = true ) {
		parent::__construct($autoload);
	}

	protected function autoload() {
		// Global.
		$this->data['bad_user_agents'] = $this->bad_user_agents();
		$this->data['bad_usernames'] = $this->bad_usernames();
		add_action('after_setup_theme', array( $this, 'global_after_setup_theme' ), 2);
		add_filter('wp_login_errors', array( $this, 'global_wp_login_errors' ), 20, 2);
		add_filter('illegal_user_logins', array( $this, 'global_illegal_user_logins' ), 20);
		if ( is_public() ) {
			// Public.
			add_filter('request', array( $this, 'public_request' ), 9);
		}
		parent::autoload();
	}

	// Global.

	public function global_after_setup_theme() {
		if ( ! $this->is_filter_active(__FUNCTION__) ) {
			return;
		}
		if ( ht_is_user_logged_in() ) {
			return;
		}
		if ( isset($_SERVER['HTTP_USER_AGENT']) && ! empty($_SERVER['HTTP_USER_AGENT']) ) {
			$callback = function ( $v ) {
				return str_contains($_SERVER['HTTP_USER_AGENT'], $v);
			};
			$tmp = array_filter($this->data['bad_user_agents'], $callback);
			if ( count($tmp) > 0 ) {
				$this->die();
			}
		}
	}

	public function global_wp_login_errors( $errors, $redirect_to ) {
		if ( ! $this->is_filter_active(__FUNCTION__) ) {
			return $errors;
		}
		if ( is_a($errors, 'WP_Error') ) {
			if ( in_array('invalid_username', $errors->get_error_codes()) ) {
				$tmp = $errors->get_error_message('invalid_username');
				if ( preg_match_all('/<strong>([\w_ \.-@]+)<\/strong>/is', substr($tmp, strrpos($tmp, '<strong>')), $matches) ) {
					if ( isset($matches[1], $matches[1][0]) ) {
						$username = trim($matches[1][0]);
						if ( in_array($username, $this->data['bad_usernames']) ) {
							$this->die();
						}
					}
				}
			}
		}
		return $errors;
	}

	public function global_illegal_user_logins( $usernames = array() ) {
		if ( ! $this->is_filter_active(__FUNCTION__) ) {
			return $usernames;
		}
		$usernames = array_unique(array_merge($usernames, $this->data['bad_usernames']));
		sort($usernames);
		return $usernames;
	}

	// Public.

	public function public_request( $query_vars = array() ) {
		if ( ! $this->is_filter_active(__FUNCTION__) ) {
			return $query_vars;
		}
		if ( count($query_vars) === 1 && isset($query_vars['author']) ) {
			if ( in_array($query_vars['author'], $this->data['bad_usernames']) ) {
				$this->die();
			}
		}
		return $query_vars;
	}

	// Functions.

	private function bad_user_agents() {
		return array(
			'cr4',
			'libwww',
			'Nozilla',
			'pxyscand',
			// https://github.com/mitchellkrogza/apache-ultimate-bad-bot-blocker/blob/master/_generator_lists/bad-user-agents.list
			'01h4x.com',
			'360Spider',
			'404checker',
			'404enemy',
			'80legs',
			'ADmantX',
			'AIBOT',
			'ALittle Client',
			'ASPSeek',
			'Abonti',
			'Aboundex',
			'Aboundexbot',
			'Acunetix',
			'AdsTxtCrawlerTP',
			'AfD-Verbotsverfahren',
			'AhrefsBot',
			'AiHitBot',
			'Aipbot',
			'Alexibot',
			'AllSubmitter',
			'Alligator',
			'AlphaBot',
			'Anarchie',
			'Anarchy',
			'Anarchy99',
			'Ankit',
			'Anthill',
			'Apexoo',
			'Aspiegel',
			'Asterias',
			'Atomseobot',
			'Attach',
			'AwarioBot',
			'AwarioRssBot',
			'AwarioSmartBot',
			'BBBike',
			'BDCbot',
			'BDFetch',
			'BLEXBot',
			'BackDoorBot',
			'BackStreet',
			'BackWeb',
			'Backlink-Ceck',
			'BacklinkCrawler',
			'BacklinksExtendedBot',
			'Badass',
			'Bandit',
			'Barkrowler',
			'BatchFTP',
			'Battleztar Bazinga',
			'BetaBot',
			'Bigfoot',
			'Bitacle',
			'BlackWidow',
			'Black Hole',
			'Blackboard',
			'Blow',
			'BlowFish',
			'Boardreader',
			'Bolt',
			'BotALot',
			'Brandprotect',
			'Brandwatch',
			'Buck',
			'Buddy',
			'BuiltBotTough',
			'BuiltWith',
			'Bullseye',
			'BunnySlippers',
			'BuzzSumo',
			'Bytespider',
			'CATExplorador',
			'CCBot',
			'CODE87',
			'CSHttp',
			'Calculon',
			'CazoodleBot',
			'Cegbfeieh',
			'CensysInspect',
			'ChatGPT-User',
			'CheTeam',
			'CheeseBot',
			'CherryPicker',
			'ChinaClaw',
			'Chlooe',
			'Citoid',
			'Claritybot',
			'ClaudeBot',
			'Cliqzbot',
			'Cloud mapping',
			'Cocolyzebot',
			'Cogentbot',
			'Collector',
			'Copier',
			'CopyRightCheck',
			'Copyscape',
			'Cosmos',
			'Craftbot',
			'Crawling at Home Project',
			'CrazyWebCrawler',
			'Crescent',
			'CrunchBot',
			'Curious',
			'Custo',
			'CyotekWebCopy',
			'DBLBot',
			'DIIbot',
			'DSearch',
			'DTS Agent',
			'DataCha0s',
			'DatabaseDriverMysqli',
			'Demon',
			'Deusu',
			'Devil',
			'Digincore',
			'DigitalPebble',
			'Dirbuster',
			'Disco',
			'Discobot',
			'Discoverybot',
			'Dispatch',
			'DittoSpyder',
			'DnBCrawler-Analytics',
			'DnyzBot',
			'DomCopBot',
			'DomainAppender',
			'DomainCrawler',
			'DomainSigmaCrawler',
			'DomainStatsBot',
			'Domains Project',
			'Dotbot',
			'Download Wonder',
			'Dragonfly',
			'Drip',
			'ECCP/1.0',
			'EMail Siphon',
			'EMail Wolf',
			'EasyDL',
			'Ebingbong',
			'Ecxi',
			'EirGrabber',
			'EroCrawler',
			'Evil',
			'Exabot',
			'Express WebPictures',
			'ExtLinksBot',
			'Extractor',
			'ExtractorPro',
			'Extreme Picture Finder',
			'EyeNetIE',
			'Ezooms',
			'FDM',
			'FHscan',
			'FacebookBot',
			'FemtosearchBot',
			'Fimap',
			'Firefox/7.0',
			'FlashGet',
			'Flunky',
			'Foobot',
			'Freeuploader',
			'FrontPage',
			'Fuzz',
			'FyberSpider',
			'Fyrebot',
			'G-i-g-a-b-o-t',
			'GPTBot',
			'GT::WWW',
			'GalaxyBot',
			'GeedoProductSearch',
			'Genieo',
			'GermCrawler',
			'GetRight',
			'GetWeb',
			'Getintent',
			'Gigabot',
			'Go!Zilla',
			'Go-Ahead-Got-It',
			'GoZilla',
			'Gotit',
			'GrabNet',
			'Grabber',
			'Grafula',
			'GrapeFX',
			'GrapeshotCrawler',
			'GridBot',
			'HEADMasterSEO',
			'HMView',
			'HTMLparser',
			'HTTP::Lite',
			'HTTrack',
			'Haansoft',
			'HaosouSpider',
			'Harvest',
			'Havij',
			'Heritrix',
			'Hloader',
			'HonoluluBot',
			'Humanlinks',
			'HybridBot',
			'IDBTE4M',
			'IDBot',
			'IRLbot',
			'Iblog',
			'Id-search',
			'IlseBot',
			'Image Fetch',
			'Image Sucker',
			'ImagesiftBot',
			'IndeedBot',
			'Indy Library',
			'InfoNaviRobot',
			'InfoTekies',
			'Information Security Team InfraSec Scanner',
			'InfraSec Scanner',
			'Intelliseek',
			'InterGET',
			'InternetMeasurement',
			'InternetSeer',
			'Internet Ninja',
			'Iria',
			'Iskanie',
			'IstellaBot',
			'JOC Web Spider',
			'JamesBOT',
			'Jbrofuzz',
			'JennyBot',
			'JetCar',
			'Jetty',
			'JikeSpider',
			'Joomla',
			'Jorgee',
			'JustView',
			'Jyxobot',
			'Kenjin Spider',
			'Keybot Translation-Search-Machine',
			'Keyword Density',
			'Kinza',
			'Kozmosbot',
			'LNSpiderguy',
			'LWP::Simple',
			'Lanshanbot',
			'Larbin',
			'Leap',
			'LeechFTP',
			'LeechGet',
			'LexiBot',
			'Lftp',
			'LibWeb',
			'Libwhisker',
			'LieBaoFast',
			'Lightspeedsystems',
			'Likse',
			'LinkScan',
			'LinkWalker',
			'Linkbot',
			'LinkextractorPro',
			'LinkpadBot',
			'LinksManager',
			'LinqiaMetadataDownloaderBot',
			'LinqiaRSSBot',
			'LinqiaScrapeBot',
			'Lipperhey',
			'Lipperhey Spider',
			'Litemage_walker',
			'Lmspider',
			'Ltx71',
			'MFC_Tear_Sample',
			'MIDown tool',
			'MIIxpc',
			'MJ12bot',
			'MQQBrowser',
			'MSFrontPage',
			'MSIECrawler',
			'MTRobot',
			'Mag-Net',
			'Magnet',
			'Mail.RU_Bot',
			'Majestic-SEO',
			'Majestic12',
			'Majestic SEO',
			'MarkMonitor',
			'MarkWatch',
			'Mass Downloader',
			'Masscan',
			'Mata Hari',
			'MauiBot',
			'Mb2345Browser',
			'MeanPath Bot',
			'Meanpathbot',
			'Mediatoolkitbot',
			'MegaIndex.ru',
			'Metauri',
			'MicroMessenger',
			'Microsoft Data Access',
			'Microsoft URL Control',
			'Minefield',
			'Mister PiX',
			'Moblie Safari',
			'Mojeek',
			'Mojolicious',
			'MolokaiBot',
			'Morfeus Fucking Scanner',
			'Mozlila',
			'Mr.4x3',
			'Msrabot',
			'Musobot',
			'NICErsPRO',
			'NPbot',
			'Name Intelligence',
			'Nameprotect',
			'Navroad',
			'NearSite',
			'Needle',
			'Nessus',
			'NetAnts',
			'NetLyzer',
			'NetMechanic',
			'NetSpider',
			'NetZIP',
			'Net Vampire',
			'Netcraft',
			'Nettrack',
			'Netvibes',
			'NextGenSearchBot',
			'Nibbler',
			'Niki-bot',
			'Nikto',
			'NimbleCrawler',
			'Nimbostratus',
			'Ninja',
			'Nmap',
			'Nuclei',
			'Nutch',
			'Octopus',
			'Offline Explorer',
			'Offline Navigator',
			'OnCrawl',
			'OpenLinkProfiler',
			'OpenVAS',
			'Openfind',
			'Openvas',
			'OrangeBot',
			'OrangeSpider',
			'OutclicksBot',
			'OutfoxBot',
			'PECL::HTTP',
			'PHPCrawl',
			'POE-Component-Client-HTTP',
			'PageAnalyzer',
			'PageGrabber',
			'PageScorer',
			'PageThing.com',
			'Page Analyzer',
			'Pandalytics',
			'Panscient',
			'Papa Foto',
			'Pavuk',
			'PeoplePal',
			'Petalbot',
			'Pi-Monster',
			'Picscout',
			'Picsearch',
			'PictureFinder',
			'Piepmatz',
			'Pimonster',
			'Pixray',
			'PleaseCrawl',
			'Pockey',
			'ProPowerBot',
			'ProWebWalker',
			'Probethenet',
			'Proximic',
			'Psbot',
			'Pu_iN',
			'Pump',
			'PxBroker',
			'PyCurl',
			'QueryN Metasearch',
			'Quick-Crawler',
			'RSSingBot',
			'Rainbot',
			'RankActive',
			'RankActiveLinkBot',
			'RankFlex',
			'RankingBot',
			'RankingBot2',
			'Rankivabot',
			'RankurBot',
			'Re-re',
			'ReGet',
			'RealDownload',
			'Reaper',
			'RebelMouse',
			'Recorder',
			'RedesScrapy',
			'RepoMonkey',
			'Ripper',
			'RocketCrawler',
			'Rogerbot',
			'SBIder',
			'SEOkicks',
			'SEOkicks-Robot',
			'SEOlyt',
			'SEOlyticsCrawler',
			'SEOprofiler',
			'SEOstats',
			'SISTRIX',
			'SMTBot',
			'SalesIntelligent',
			'ScanAlert',
			'Scanbot',
			'ScoutJet',
			'Scrapy',
			'Screaming',
			'ScreenerBot',
			'ScrepyBot',
			'Searchestate',
			'SearchmetricsBot',
			'Seekport',
			'SeekportBot',
			'SemanticJuice',
			'Semrush',
			'SemrushBot',
			'SemrushBot-BA',
			'SemrushBot-FT',
			'SemrushBot-OCOB',
			'SemrushBot-SI',
			'SemrushBot-SWA',
			'SentiBot',
			'SenutoBot',
			'SeoCherryBot',
			'SeoSiteCheckup',
			'SeobilityBot',
			'Seomoz',
			'Shodan',
			'Siphon',
			'SiteAuditBot',
			'SiteCheckerBotCrawler',
			'SiteExplorer',
			'SiteLockSpider',
			'SiteSnagger',
			'SiteSucker',
			'Site Sucker',
			'Sitebeam',
			'Siteimprove',
			'Sitevigil',
			'SlySearch',
			'SmartDownload',
			'Snake',
			'Snapbot',
			'Snoopy',
			'SocialRankIOBot',
			'Sociscraper',
			'Sogou web spider',
			'Sosospider',
			'Sottopop',
			'SpaceBison',
			'Spammen',
			'SpankBot',
			'Spanner',
			'Spbot',
			'Spider_Bot',
			'Spider_Bot/3.0',
			'Spinn3r',
			'SplitSignalBot',
			'SputnikBot',
			'Sqlmap',
			'Sqlworm',
			'Sqworm',
			'Steeler',
			'Stripper',
			'Sucker',
			'Sucuri',
			'SuperBot',
			'SuperHTTP',
			'Surfbot',
			'SurveyBot',
			'Suzuran',
			'Swiftbot',
			'Szukacz',
			'T0PHackTeam',
			'T8Abot',
			'Teleport',
			'TeleportPro',
			'Telesoft',
			'Telesphoreo',
			'Telesphorep',
			'TheNomad',
			'The Intraformant',
			'Thumbor',
			'TightTwatBot',
			'TinyTestBot',
			'Titan',
			'Toata',
			'Toweyabot',
			'Tracemyfile',
			'Trendiction',
			'Trendictionbot',
			'True_Robot',
			'Turingos',
			'Turnitin',
			'TurnitinBot',
			'TwengaBot',
			'Twice',
			'Typhoeus',
			'URLy.Warning',
			'URLy Warning',
			'UnisterBot',
			'Upflow',
			'V-BOT',
			'VB Project',
			'VCI',
			'Vacuum',
			'Vagabondo',
			'VelenPublicWebCrawler',
			'VeriCiteCrawler',
			'VidibleScraper',
			'Virusdie',
			'VoidEYE',
			'Voil',
			'Voltron',
			'WASALive-Bot',
			'WBSearchBot',
			'WEBDAV',
			'WISENutbot',
			'WPScan',
			'WWW-Collector-E',
			'WWW-Mechanize',
			'WWW::Mechanize',
			'WWWOFFLE',
			'Wallpapers',
			'Wallpapers/3.0',
			'WallpapersHD',
			'WeSEE',
			'WebAuto',
			'WebBandit',
			'WebCollage',
			'WebCopier',
			'WebEnhancer',
			'WebFetch',
			'WebFuck',
			'WebGo IS',
			'WebImageCollector',
			'WebLeacher',
			'WebPix',
			'WebReaper',
			'WebSauger',
			'WebStripper',
			'WebSucker',
			'WebWhacker',
			'WebZIP',
			'Web Auto',
			'Web Collage',
			'Web Enhancer',
			'Web Fetch',
			'Web Fuck',
			'Web Pix',
			'Web Sauger',
			'Web Sucker',
			'Webalta',
			'WebmasterWorldForumBot',
			'Webshag',
			'WebsiteExtractor',
			'WebsiteQuester',
			'Website Quester',
			'Webster',
			'Whack',
			'Whacker',
			'Whatweb',
			'Who.is Bot',
			'Widow',
			'WinHTTrack',
			'WiseGuys Robot',
			'Wonderbot',
			'Woobot',
			'Wotbox',
			'Wprecon',
			'Xaldon WebSpider',
			'Xaldon_WebSpider',
			'Xenu',
			'YaK',
			'YoudaoBot',
			'Zade',
			'Zauba',
			'Zermelo',
			'Zeus',
			'Zitebot',
			'ZmEu',
			'ZoomBot',
			'ZoominfoBot',
			'ZumBot',
			'ZyBorg',
			'adscanner',
			'anthropic-ai',
			'archive.org_bot',
			'arquivo-web-crawler',
			'arquivo.pt',
			'autoemailspider',
			'awario.com',
			'backlink-check',
			'cah.io.community',
			'check1.exe',
			'clark-crawler',
			'coccocbot',
			'cognitiveseo',
			'cohere-ai',
			'com.plumanalytics',
			'crawl.sogou.com',
			'crawler.feedback',
			'crawler4j',
			'dataforseo.com',
			'dataforseobot',
			'demandbase-bot',
			'domainsproject.org',
			'eCatch',
			'evc-batch',
			'everyfeed-spider',
			'facebookscraper',
			'gopher',
			'heritrix',
			'imagesift.com',
			'instabid',
			'internetVista monitor',
			'ips-agent',
			'isitwp.com',
			'iubenda-radar',
			'linkdexbot',
			'linkfluence',
			'lwp-request',
			'lwp-trivial',
			'magpie-crawler',
			'meanpathbot',
			'mediawords',
			'muhstik-scan',
			'netEstate NE Crawler',
			'oBot',
			'omgili',
			'openai',
			'openai.com',
			'page scorer',
			'pcBrowser',
			'plumanalytics',
			'polaris version',
			'probe-image-size',
			'ripz',
			's1z.ru',
			'satoristudio.net',
			'scalaj-http',
			'scan.lol',
			'seobility',
			'seocompany.store',
			'seoscanners',
			'seostar',
			'serpstatbot',
			'sexsearcher',
			'sitechecker.pro',
			'siteripz',
			'sogouspider',
			'sp_auditbot',
			'spyfu',
			'sysscan',
			'tAkeOut',
			'trendiction.com',
			'trendiction.de',
			'ubermetrics-technologies.com',
			'voyagerx.com',
			'webgains-bot',
			'webmeup-crawler',
			'webpros.com',
			'webprosbot',
			'x09Mozilla',
			'x22Mozilla',
			'xpymep1.exe',
			'zauba.io',
			'zgrab',
		);
	}

	private function bad_usernames() {
		list($host,) = explode('.', wp_parse_url(home_url(), PHP_URL_HOST));
		return array(
			$host,
			'admin',
			'admindemo',
			'administrator',
			'blog',
			'blogs',
			'content',
			'demo',
			'developer',
			'editor',
			'file',
			'files',
			'invite',
			'main',
			'member',
			'members',
			'plugin',
			'plugins',
			'root',
			'site',
			'sites',
			'subscriber',
			'test',
			'theme',
			'themes',
			'user',
			'users',
			'web',
			'webmaster',
			'wordpress',
			'wp-admin',
			'wp-content',
			'wp-includes',
			'wpadmin',
			'wpcontent',
			'wpincludes',
			'www',
		);
	}

	private function die() {
		// plugins/wp-cerber.
		if ( function_exists('cerber_get_block') && function_exists('cerber_block_add') ) {
			if ( ! cerber_get_block() ) {
				cerber_block_add(null, 704);
			}
		}
		// Send bad actors to their own IP.
		$this->load_functions('php-network');
		if ( $ip = get_visitor_ip() ) {
			$this->load_functions('wp-pluggable');
			if ( ht_wp_redirect('http://' . $ip) ) {
				exit;
			}
		}
		// Bad Request.
		status_header(400);
		wp_die(get_status_header_desc(400), 400);
	}
}
